[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "karrio_advisor_nordic_conventions"
version = "2026.10.6"
description = "Karrio - Nordic trade document conventions advisors"
readme = "README.md"
requires-python = ">=3.11"
license = "LGPL-3.0"
authors = [
    {name = "PrimePack AB"}
]
classifiers = [
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "karrio",
]

[project.urls]
Homepage = "https://github.com/PrimePack-AB/karrio-advisor-nordic-conventions"

[project.entry-points."karrio.plugins"]
advisor_nordic_conventions = "karrio.plugins.advisor_nordic_conventions:METADATA"

[tool.setuptools]
zip-safe = false
include-package-data = true

[tool.setuptools.package-dir]
"" = "."

[tool.setuptools.packages.find]
include = ["karrio*"]
exclude = ["tests.*", "tests"]
namespaces = true
